// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTinder.Context;

namespace MovieTinder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201009211624_MovieModelSeedData")]
    partial class MovieModelSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieTinder.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Nightmare Before Christmas"
                        },
                        new
                        {
                            Id = 2,
                            Title = "28 Days Later"
                        },
                        new
                        {
                            Id = 3,
                            Title = "P.S. I Love You"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
